devices:
  - name:                   'grill'                  # Unique name of the device
    type:                   'igrill_v3'              # Supported devices: igrill_mini, igrill_v2, igrill_v3, pulse_2000
    address:                '70:91:8F:06:E9:C7'      # The MAC of the device
    topic:                  'temperature/outside'    # The topic to publish on. will have name and probe number appended: <topic>/<name>/probe{1..4}
    interval:               20                       # Polling interval
#   publish_missing_probes: False                    # Optional default False - Enable sending a value for non-connected probes
#   missing_probe_value:    'missing'                # Optional default 'missing' - Value to send if publish_missing_probes is True
